### PR TITLE
fix 'Netd : Unable to start DnsProxyListner' boot loop

### PR DESCRIPTION
**Pull request by stellirin**
Updates to CyanogenMod/android_system_netd break thunderg builds

### CODE REVIEW

**Comment by mik9** [comment]
Oops. Custom init.rc is no longer needed.
to make swap_volume_keys_orientation work: http://review.cyanogenmod.com/#change,5607

**Comment by stellirin** [comment]
oops the volume key comment wasn't supposed to be pushed, but the DnsProxyLisner boot loop is still a valid fix :o)

**Comment by mik9** [comment]
This one is better: https://github.com/mik9/android_device_lge_thunderg/commit/0b162f6483c5b5a9cd57bd0771cac9b4b5aaa73a :)

**Comment by stellirin** [comment]
are you sure that is all that is needed? I'll give it a go but nothing I tried would get the new netd to work until I added the line 'socket dnsproxyd stream 0660 root inet'

**Comment by mik9** [comment]
This line was [added](https://github.com/CyanogenMod/android_system_core/commit/4cae3fa3d6281bcd05419fbf8d5f2192ebd79379#rootdir/init.rc) into origianl init.rc (system/core/rootdir/init.rc). The original init.rc was overwritten by custom and seems I forget to remove my custom init.rc (which was needed to fix wired headset media button).

**Comment by stellirin** [comment]
super, thanks for the info, I didn't think to check for the original...

**Pull request closed without merging**
